#+title: Readme
#+options: toc:1

* COA256 Coursework

1. [[file:README.org::Dependencies][Dependencies]]
2. [[Project Overview][Project Overview]]
3. [[Building from Source][Building from Source]]
4. [[Resources][Resources]]

** Dependencies
| Plugins   | Justification                                    |
| [[https://openjfx.io/][JavaFX 19]] | A modern successor to Java's internal Swing API  |
| [[https://github.com/johnrengelman/shadow][Shadow]]    | Allows the creation of "fat" ~.jar~ files        |
| [[https://github.com/iAmGio/animated][animated]]  | A library of Flutter-style animations for JavaFX |
| [[https://github.com/kordamp/ikonli][Ikonli]]    | Provides access to the Bootstrap icon set        |

** Project Overview
Broadly, this project consists of two components.

The first is a fairly generic set of classes for handling
dummy book and user data, and mainly exists to demonstrate
common OOP principles (inheritance, abstraction, interfaces),
as well as some more advanced concepts (nested objects,
records, builders).

The second is the actual UI component, built using JavaFX.
~TODO: finish this part~

** Building from Source
#+begin_quote
Gradle generates two files: ~./gradlew~ and ~./gradlew.bat~, to handle gradle tasks on systems that don't actually have Gradle installed. The command ~gradle TASK~ can be replaced with ~./gradlew TASK~ (on unix systems) or ~.gradlew.bat TASK~ (on Windows).
#+end_quote

From the root directory of the project, run the following command:

#+begin_src shell
# if you're on a unix system
./gradlew buildRelease

# if you're on Windows
./gradlew.bat buildRelease
#+end_src

This will generate a zip archive in ~./build/distributions~ containing unix and Windows binaries for the app, and a self-contained ~.jar~ (generated by Shadow), which can be run on any system with a compatible Java version.

If you'd like the project as it was submitted, run the following command:

#+begin_src shell
# if you're on a unix system
./gradlew buildSubmission

# if you're on Windows
./gradlew.bat buildSubmission
#+end_src

This command will do the same as buildRelease, while also adding in the source files and some Eclipse compatibility files. Those are just there to ensure that when run in the target context (in Eclipse on Windows 10), no additional configuration is required.

** Resources
- [[https://jenkov/com/tutorials/javafx/index.html][jenkov.com]]
- [[https://imperceptiblethoughts/com/shadow/][Shadow Documentation]]
- [[https://stackoverflow.com/a/70864141][Stack Overflow: Configuring Shadow]]
- [[https://github.com/mhrimaz/AwesomeJavaFX][Awesome JavaFX]]
- [[https://kordamp.org/ikonli/#_introduction][Ikonli Documentation]]
- [[https://github.com/iAmGio/animated][animated]]
